### ISSUE TITLE
What does "at least one javascript framework" really mean in the job description?

### ISSUE THREAD

**Issue by artych** [embersherpa/ama#23]
There are many jobs with a such requirement "... good knowledge of at least one framework, i.e.: AngularJS, Ember.js, Backbone.js".

I personally know ember, and I'd like to develop ember-cli apps. What should I expect from such a job? I see many options:
- Company is large, there are many projects for every javascript framework. (But why not to choose the best one ?)
- If you know at least one of them, you will quickly learn others. (I think you'll need 1-2 month to learn ember (on ember-cli with ember-data) and produce production-ready code and tests, because of many gotchas. And also will company wait till I learn AngularJS and Backbone.js?)
- We really work with AngularJS only, but we like to collect front-end developers CVs.

Thank you for answer!

**Comment by taras** [comment]
> There are many jobs with a such requirement "... good knowledge of at least one framework, i.e.: AngularJS, Ember.js, Backbone.js".

It usually means that they want you to have experience building SPA apps. Some companies, like Soundcloud and Netflix, use many frameworks and allow each individual team to choose a framework that's appropriate for the project. 

I was once hired by a company that listed all 3 on their job application but they were really looking to hire someone who would own the frontend application, so they didn't really care what was used as long as you were good at it.

There are also companies that just don't care about technology (a lot of agencies are like this); they've heard buzz words but what they really care is that you deliver the project.

> I personally know ember, and I'd like to develop ember-cli apps

I recommend developers who like Ember to focus on companies that are specifically hiring Ember developers because these companies already drank the Ember Coolaid. It's usually easy to work with companies that see Ember as an investment with it's plusses and accepting that there are also minuses. It also helps that Ember market is very hot and there are companies that would put high value on Ember experience rather than just any SPA experience.

**Comment by artych** [comment]
Thanks @taras, it's very helpful.
